---
-   hosts: solr_build
    gather_facts: True         
    vars:
      dir_code_src: '~/code/'
      dir_servers: '~/servers/'
    tasks:
    - name: get public ip
      shell:  GET http://169.254.169.254/latest/meta-data/public-ipv4
      register: public_ip
    - name: 


#sudo tar -cvf solr-latest-index.tar /home/solr/servers/solr/dc-collection/data/index
#sudo chown ec2-user:ec2-user solr-latest-index.tar
#bzip2 solr-latest-index.tar
#scp solr-latest-index.tar.bz2 10.0.0.68:
#rm solr-latest-index.tar

